# Generated by Django 4.0.8 on 2023-11-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_job_user_about_user_address_user_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Erkak', 'Male'), ('Ayol', 'Female')], default='Ayol', max_length=255),
        ),
    ]
