# Generated by Django 4.1 on 2023-11-07 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_user_first_name_user_last_name_alter_user_gender"),
        ("user", "0015_alter_user_gender"),
    ]

    operations = []
