<<<<<<< HEAD
# Generated by Django 4.1 on 2023-11-07 06:46
=======
# Generated by Django 4.2.7 on 2023-11-07 07:08
>>>>>>> 9f0a0cf (add login adn register view)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("user", "0016_merge_20231107_1144"),
=======
        ("user", "0016_alter_user_gender"),
>>>>>>> 9f0a0cf (add login adn register view)
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("Erkak", "Male"), ("Ayol", "Female")],
                default="Ayol",
                max_length=255,
            ),
        ),
    ]
