# Generated by Django 4.1 on 2023-11-07 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_user_gender'),
        ('user', '0020_remove_user_password1_alter_user_gender'),
        ('user', '0025_alter_user_gender'),
    ]

    operations = [
    ]
